import type { ClusterData } from "./types/clusterData";

export const clusterData: ClusterData[] = [
  {
    name: "Cluster A",
    cpu: 2463,
    ram: 1368,
    storage: 246,
    network: 307,
    gpu: 821,
    efficiency: 10,
    total: 6867,
  },
  {
    name: "Cluster B",
    cpu: 2127,
    ram: 1181,
    storage: 212,
    network: 265,
    gpu: 0,
    efficiency: 28,
    total: 5574,
  },
  {
    name: "Cluster C",
    cpu: 1733,
    ram: 962,
    storage: 173,
    network: 216,
    gpu: 577,
    efficiency: 15,
    total: 4664,
  },
  {
    name: "Cluster D",
    cpu: 1218,
    ram: 677,
    storage: 121,
    network: 152,
    gpu: 0,
    efficiency: 50,
    total: 2545,
  },
];

export const namespaceData: Record<string, ClusterData[]> = {
  "Cluster A": [
    {
      name: "Namespace A",
      cpu: 1231,
      ram: 684,
      storage: 123,
      network: 153,
      gpu: 410,
      efficiency: 5,
      total: 3433,
    },
    {
      name: "Namespace B",
      cpu: 739,
      ram: 410,
      storage: 73,
      network: 92,
      gpu: 246,
      efficiency: 20,
      total: 2060,
    },
    {
      name: "Namespace C",
      cpu: 369,
      ram: 205,
      storage: 36,
      network: 46,
      gpu: 123,
      efficiency: 50,
      total: 1030,
    },
    {
      name: "Namespace D",
      cpu: 123,
      ram: 68,
      storage: 12,
      network: 15,
      gpu: 41,
      efficiency: 40,
      total: 343,
    },
  ],
  "Cluster B": [
    {
      name: "Namespace A",
      cpu: 1063,
      ram: 590,
      storage: 106,
      network: 132,
      gpu: 0,
      efficiency: 15,
      total: 1891,
    },
    {
      name: "Namespace B",
      cpu: 638,
      ram: 354,
      storage: 63,
      network: 79,
      gpu: 0,
      efficiency: 30,
      total: 1134,
    },
    {
      name: "Namespace C",
      cpu: 319,
      ram: 177,
      storage: 31,
      network: 39,
      gpu: 0,
      efficiency: 25,
      total: 566,
    },
    {
      name: "Namespace D",
      cpu: 107,
      ram: 59,
      storage: 10,
      network: 13,
      gpu: 0,
      efficiency: 50,
      total: 189,
    },
  ],
  "Cluster C": [
    {
      name: "Namespace A",
      cpu: 866,
      ram: 481,
      storage: 86,
      network: 108,
      gpu: 288,
      efficiency: 12,
      total: 1829,
    },
    {
      name: "Namespace B",
      cpu: 520,
      ram: 288,
      storage: 52,
      network: 64,
      gpu: 173,
      efficiency: 18,
      total: 1097,
    },
    {
      name: "Namespace C",
      cpu: 260,
      ram: 144,
      storage: 26,
      network: 32,
      gpu: 86,
      efficiency: 35,
      total: 548,
    },
    {
      name: "Namespace D",
      cpu: 87,
      ram: 48,
      storage: 8,
      network: 10,
      gpu: 30,
      efficiency: 40,
      total: 183,
    },
  ],
  "Cluster D": [
    {
      name: "Namespace A",
      cpu: 609,
      ram: 338,
      storage: 60,
      network: 76,
      gpu: 0,
      efficiency: 20,
      total: 1083,
    },
    {
      name: "Namespace B",
      cpu: 365,
      ram: 203,
      storage: 36,
      network: 45,
      gpu: 0,
      efficiency: 30,
      total: 649,
    },
    {
      name: "Namespace C",
      cpu: 182,
      ram: 101,
      storage: 18,
      network: 22,
      gpu: 0,
      efficiency: 40,
      total: 323,
    },
    {
      name: "Namespace D",
      cpu: 62,
      ram: 34,
      storage: 6,
      network: 7,
      gpu: 0,
      efficiency: 50,
      total: 110,
    },
  ],
};

export const podData: Record<string, Record<string, ClusterData[]>> = {
  "Cluster A": {
    "Namespace A": [
      {
        name: "Pod A",
        cpu: 862,
        ram: 479,
        storage: 86,
        network: 107,
        gpu: 410,
        efficiency: 8,
        total: 2403,
      },
      {
        name: "Pod B",
        cpu: 246,
        ram: 136,
        storage: 24,
        network: 30,
        gpu: 246,
        efficiency: 40,
        total: 686,
      },
      {
        name: "Pod C",
        cpu: 86,
        ram: 47,
        storage: 8,
        network: 10,
        gpu: 123,
        efficiency: 35,
        total: 240,
      },
      {
        name: "Pod D",
        cpu: 36,
        ram: 20,
        storage: 3,
        network: 60,
        gpu: 41,
        efficiency: 70,
        total: 103,
      },
    ],
    "Namespace B": [
      {
        name: "Pod E",
        cpu: 420,
        ram: 233,
        storage: 42,
        network: 52,
        gpu: 120,
        efficiency: 18,
        total: 867,
      },
      {
        name: "Pod F",
        cpu: 210,
        ram: 116,
        storage: 21,
        network: 26,
        gpu: 60,
        efficiency: 30,
        total: 433,
      },
      {
        name: "Pod G",
        cpu: 105,
        ram: 58,
        storage: 10,
        network: 13,
        gpu: 30,
        efficiency: 42,
        total: 216,
      },
    ],
    "Namespace C": [
      {
        name: "Pod H",
        cpu: 180,
        ram: 100,
        storage: 18,
        network: 22,
        gpu: 50,
        efficiency: 25,
        total: 370,
      },
      {
        name: "Pod I",
        cpu: 120,
        ram: 66,
        storage: 12,
        network: 15,
        gpu: 35,
        efficiency: 35,
        total: 248,
      },
    ],
  },
};
